/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HRM;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author KaraWalters
 */
public class NewJFrame1 extends javax.swing.JFrame {

    
    public NewJFrame1() {
        initComponents();
        jTextField3.setText(String.valueOf(HRMM.RoomData.get(0).RoomPrice));
        jTextField3.setEditable(false);
        ArrayList<String> items = new ArrayList<>();
        for (int i = 0; i < HRMM.RoomData.size(); i++) {

            if (HRMM.RoomData.get(i).isAvailable) {

                items.add(String.valueOf(HRMM.RoomData.get(i).Room));

            }

        }

        String[] itemCollections = new String[items.size()];

        for (int i = 0; i < items.size(); i++) {

            itemCollections[i] = items.get(i);

        }

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(itemCollections));

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {


        int index = jComboBox1.getSelectedIndex();
        jTextField3.setText(String.valueOf(HRMM.RoomData.get(index).RoomPrice));

    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {

        this.setVisible(false);
        NewJFrame2 menuframe = new NewJFrame2();
        menuframe.setVisible(true);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

        String name = jTextField1.getText();
        String cnic = jTextField2.getText();
        int room = HRMM.RoomData.get(jComboBox1.getSelectedIndex()).Room;
        int roomprice = HRMM.RoomData.get(jComboBox1.getSelectedIndex()).RoomPrice;

        if (!name.equals("") && !cnic.equals("")) {

            Room r = HRMM.RoomData.get(jComboBox1.getSelectedIndex());

            r.CustomerName = name;
            r.Room = room;
            r.RoomPrice = roomprice;
            r.isAvailable = false;

            this.setVisible(false);

            NewJFrame2 menuframe = new NewJFrame2();
            menuframe.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Empty field found");
        }
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

// Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
// End of variables declaration
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

